<?php 
/**
 * Cecropia Advanced Online Customers Extension
 *
 * NOTICE OF LICENSE
 *
 *
 * @version     0.1.0
 * @category    Cecropia
 * @package     Cecropia_AdvancedOC
 * @copyright   Copyright (c) 2013
 * @license
 */

/**
 * Ip Geolocation and Additional Info Template
 *
 * @category   Cecropia
 * @package    Cecropia_AdvancedOC
 * @author     Mohammed NAHHAS <m.nahhas@live.fr>
 */
?>
<div class="content-header">
	<table cellspacing="0">
	    <tr>
	        <td style="width:50%;"><h3 class="icon-head head-online-visitors"><?php echo $this->getTitle() ?></h3></td>
	        <td class="a-right">
	            <?php echo $this->getButtonsHtml() ?>
	        </td>
	    </tr>
	</table>
</div>

<div class="cecropia-advancedoc">
    <table cellspacing="0" width="100%">
        <tr>
            <td class="left-col">
				<div>
					<?php echo $this->getIframe(); ?>
				</div>
            </td>
            <td class="right-col">
				<div>
					<?php echo $this->getAdditionalInfo(); ?>
				</div>
            </td>
        </tr>
    </table>
</div>